@startmindmap
* Главная страница
** Регистрация / Вход
*** Личный кабинет
**** Список маршрутов пользователя
**** Детали маршрута (PDF, карта)
** Выбор параметров маршрута
*** Форма параметров (дни, транспорт, дети, доступность)
**** Результаты поиска маршрутов
***** Просмотр маршрута
***** Визуализация маршрута на карте
***** Скачать маршрут в PDF
** Информация о сервисе
** Отзывы и поддержка
@endmindmap
